################################################################################
# Usefull stuff you do WANT for all repositories.
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.3.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-json
    -   id: check-toml
   #-   id: debug-statements  # Python only!
   #-   id: fix-encoding-pragma  # Python only!
-   repo: https://github.com/codespell-project/codespell
    rev: v2.0.0
    hooks:
    -   id: codespell
        args: [-L, ""]
################################################################################
# Go lang specific.
#- repo: git://github.com/dnephin/pre-commit-golang
#  rev: master
#  hooks:
#    - id: go-fmt
#    - id: go-vet
#    - id: go-lint
#    - id: go-imports
#    - id: go-cyclo
#      args: [-over=15]  # 15 is a reasonable number, maybe?
#    - id: validate-toml
#    - id: golangci-lint
#    - id: go-critic
#    - id: go-unit-tests
#    - id: go-build
#- repo: git://github.com/Bahjat/pre-commit-golang
#  rev: master
#  hooks:
#    #- id: gofumpt # requires https://github.com/mvdan/gofumpt
#    - id: go-err-check # requires https://github.com/kisielk/errcheck
#    - id: go-static-check # install https://staticcheck.io/docs/
################################################################################
# Python specific.
# - repo: https://github.com/psf/black
#   rev: 19.10b0
#   hooks:
#     -   id: black
# - repo: https://github.com/Lucas-C/pre-commit-hooks-safety
#   rev: v1.1.0
#   hooks:
#     -   id: python-safety-dependencies-check
# # Statically populate the known_third_party isort setting.
# - repo: https://github.com/asottile/seed-isort-config
#   rev: v1.9.4
#   hooks:
#     -   id: seed-isort-config
# - repo: https://github.com/pre-commit/mirrors-isort
#   rev: v4.3.21  # Use the revision sha / tag you want to point at
#   hooks:
#     -   id: isort
# - repo: https://github.com/myint/docformatter
#   rev: v1.3.1
#   hooks:
#     -   id: docformatter
# - repo: https://gitlab.com/smop/pre-commit-hooks
#   rev: v1.0.0
#   hooks:
#     - id: check-poetry
# - repo: https://github.com/Lucas-C/pre-commit-hooks-bandit
#   sha: v1.0.4
#   hooks:
#     - id: python-bandit-vulnerability-check
#       args: [--verbose, --ini, .banditrc, -ll, --skip, "B321,B402", --recursive, src/lib]
-   repo: https://github.com/jorisroovers/gitlint
    rev: v0.14.0
    hooks:
    -   id: gitlint
